<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FUN_Scale" Id="{1c1ac60c-044b-45f3-a557-1f12955d0200}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FUN_Scale : REAL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FUN_Scale">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>